version: '3'  
services:  
  app:
    build:
      context: ./app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONIOENCODING=UTF-8
    ports:
      - "5000:5000"
    tty: true
    volumes:
        - ./app:/user/app
    working_dir: /user/app
    
  redis:
    image: redis
    volumes:
      - ./r_data:/redis_data
